language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION="^3.4"
  - COMPOSER_FLAGS=""

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi;

install:
  - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/simple-phpunit

notifications:
  email: info@endroid.nl
